
namespace DocxCorrector.Models
{
    // Свойства параграфа
    public class ParagraphProperties
    {
        // Range
        public string Text { get; set; }
        public string Bold { get; set; }
        public string Italic { get; set; }
        public string Underline { get; set; }
        public string BoldBi { get; set; }
        public string Bookmarks { get; set; }
        public string Borders { get; set; }
        public string Case { get; set; }
        public string Characters { get; set; }
        public string CharacterWidth { get; set; }
        public string CombineCharacters { get; set; }
        public string ContentControls { get; set; }
        public string Creator { get; set; }
        public string DisableCharacterSpaceGrid { get; set; }
        public string Document { get; set; }
        public string Duplicate { get; set; }
        public string Editors { get; set; }
        public string EmpasisMark { get; set; }
        public string End { get; set; }
        public string EndnoteOptions { get; set; }
        public string Endnotes { get; set; }
        public string Fields { get; set; }
        public string Find { get; set; }
        public string FitTextWidth { get; set; }
        public string Footnotes { get; set; }
        public string FormattedText { get; set; }
        public string FormFields { get; set; }
        public string Frames { get; set; }
        public string GrammarChecked { get; set; }
        public string GrammaticalErrors { get; set; }
        public string HighlightColorIndex { get; set; }
        public string HorizontallnVertical { get; set; }
        public string HTMLDicisions { get; set; }
        public string Hyperlinks { get; set; }
        public string InlineShapes { get; set; }
        public string IsEndOfMark { get; set; }
        public string ItalicBi { get; set; }
        public string Kana { get; set; }
        public string LanguageDetected { get; set; }
        public string LanguageID { get; set; }
        public string LanguageIDFarEst { get; set; }
        public string LanguageIDOther { get; set; }
        public string ListFormat { get; set; }
        public string ListParagraphs { get; set; }
        public string NoProofing { get; set; }
        public string OMaths { get; set; }
        public string Orientation { get; set; }
        public string PageSetup { get; set; }
        public string ParagraphFormat { get; set; }
        public string Paragraphs { get; set; }
        public string PreviousBookmarkID { get; set; }
        public string ReadabilityStatistics { get; set; }
        public string Revisions { get; set; }
        public string Sections { get; set; }
        // Интересно
        public string Sentenses { get; set; }
        public string Shading { get; set; }
        public string ShapeRange { get; set; }
        public string ShowAll { get; set; }
        public string SmartTags { get; set; }
        public string SpellingChecked { get; set; }
        public string SpellingErrors { get; set; }
        public string Subdocuments { get; set; }
        public string SynonymInfo { get; set; }
        public string Tables { get; set; }
        public string TextRetrievalMode { get; set; }
        public string TextVisibleOnScreen { get; set; }
        public string TopLevelTables { get; set; }
        public string TwoLinesInOne { get; set; }
        //public string WordOpenXML { get; set; }
        public string Words { get; set; }
        //public string XML { get; set; }
        //public string XMLNodes { get; set; }
        // Font
        public string FontName { get; set; }
        public string FontSize { get; set; }
        public string FontTextColorRGB { get; set; }
        public string FontUnderlineColor { get; set; }        
        public string FontStrikeThrough { get; set; }
        public string FontSuperscript { get; set; }
        public string FontSubscript { get; set; }
        public string FontHidden { get; set; }
        public string FontScaling { get; set; }
        public string FontPosition { get; set; }
        public string FontKerning { get; set; }
        public string FontAllCaps { get; set; }
        public string FontApplication { get; set; }
        public string FontBoldBi { get; set; }
        public string FontBorders { get; set; }
        public string FontColor { get; set; }
        public string FontColorIndex { get; set; }
        public string FontColorIndexBi { get; set; }
        public string FontContextualAlternates { get; set; }
        public string FontCreator { get; set; }
        public string FontDiacriricColor { get; set; }
        public string FontDoubleStrikeThrough { get; set; }
        public string FontDuplicate { get; set; }
        public string FontEmboss { get; set; }
        public string FontEmphasisMark { get; set; }
        public string FontEngrave { get; set; }
        public string FontFill { get; set; }
        public string FontGlow { get; set; }
        public string FontItalic { get; set; }
        public string FontItalicBi { get; set; }
        public string FontLigatures { get; set; }
        public string FontNameAscii { get; set; }
        public string FontNameBi { get; set; }
        public string FontNameFarEast { get; set; }
        public string FontNameOther { get; set; }
        public string FontNumberForm { get; set; }
        public string FontNumberSpacing { get; set; }
        public string FontOutline { get; set; }
        public string FontParent { get; set; }
        public string FontReflection { get; set; }
        public string FontShading { get; set; }
        public string FontShadow { get; set; }
        public string FontSizeBi { get; set; }
        public string FontSmallCaps { get; set; }
        public string FontStylisticSet { get; set; }
        public string FontTextShadow { get; set; }
        public string FontThreeD { get; set; }
        public string FontUnderline { get; set; }
        // Paragraph
        public string OutlineLevel { get; set; }
        public string Alignment { get; set; }
        public string CharacterUnitLeftIndent { get; set; }
        public string LeftIndent { get; set; }
        public string CharacterUnitRightIndent { get; set; }
        public string RightIndent { get; set; }
        public string CharacterUnitFirstLineIndent { get; set; }
        public string MirrorIndents { get; set; }
        public string LineSpacing { get; set; }
        public string SpaceBefore { get; set; }
        public string SpaceAfter { get; set; }
        public string PageBreakBefore { get; set; }
        public string AddSpaceBetweenFarEastAndAlpha { get; set; }
        public string AddSpaceBetweenFarEastAndDigit { get; set; }
        public string Application { get; set; }
        public string AutoAdjustRightIndent { get; set; }
        public string BaseLineAlignment { get; set; }
        public string ParagraphBorders { get; set; }
        public string CollapsedState { get; set; }
        public string CollapseHEadingByDefault { get; set; }
        public string ParagraphCreator { get; set; }
        public string DisableLineHeightGrid { get; set; }
        public string DropCap { get; set; }
        public string FarEastLineBreakControl { get; set; }
        public string FirstLineIndent { get; set; }
        public string HalfWidthPunctuationOnTopOfLine { get; set; }
        public string HalfWidthPunctuation { get; set; }
        public string Hyphenation { get; set; }
        public string IsStyleSeparator { get; set; }
        public string KeepTogether { get; set; }
        public string KeepWithNext { get; set; }
        public string LineSpacingRule { get; set; }
        public string LineUnitAfter { get; set; }
        public string LineUnitBefore { get; set; }
        public string NoLineNumber { get; set; }
        public string ParagraphParent { get; set; }
        public string ReadingOrder { get; set; }
        public string ParagraphShading { get; set; }
        public string SpaceAfterAuto { get; set; }
        public string ParagraphStyle { get; set; }
        public string TabStops { get; set; }
        public string TextboxTightWrap { get; set; }
        public string TextID { get; set; }
        public string WindowControl { get; set; }
        public string WordWrap { get; set; }

    }
}